name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@9dc904e06dcde958bf8a0b3230715d32b9e3a85f # main
        with:
          repository: openstack/keystone
          ref: 272bcf4159fac8f795805b9f0e11b91144fb89c2 # stable/2024.2

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@9dc904e06dcde958bf8a0b3230715d32b9e3a85f # main
        with:
          image-name: keystone
          build-contexts: keystone=openstack/keystone
          push: ${{ github.event_name != 'pull_request' }}
