name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@main
        with:
          repository: openstack/keystone
          ref: bd178ee91f92f50398cf940b1db3eb2157ed7fd3 # master

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@main
        with:
          image-name: keystone
          build-contexts: keystone=openstack/keystone
          push: ${{ github.event_name != 'pull_request' }}
